### ISSUE TITLE
Install on Netlify not possible

### ISSUE THREAD

**Issue by magic-space** [maccali/Apod#9]
Please update you web app. Yarn Build && Yarn Start Not Working. Your NPM version is out of date for Netlify.

**Comment by magic-space** [comment]
1:04:09 PM: build-image version: fcb0c1b3ada6d25c1cb58e8bc514f5f23cc14f15 (focal)
1:04:09 PM: buildbot version: c32e21f337d920d500f8f7b951fd63f528c2b7b9
1:04:09 PM: Building without cache
1:04:09 PM: Starting to prepare the repo for build
1:04:09 PM: No cached dependencies found. Cloning fresh repo
1:04:09 PM: git clone --filter=blob:none https://github.com/magic-space/Apod
1:04:09 PM: Preparing Git Reference refs/heads/master
1:04:12 PM: Starting to install dependencies
1:04:14 PM: Python version set to 3.8
1:04:15 PM: Attempting Ruby version 2.7.2, read from environment
1:04:15 PM: Using Ruby version 2.7.2
1:04:16 PM: Started restoring cached go cache
1:04:16 PM: Finished restoring cached go cache
1:04:18 PM: go version go1.19.13 linux/amd64
1:04:19 PM: Using PHP version 8.0
1:04:20 PM: Downloading and installing node v14.21.3...
1:04:20 PM: Downloading https://nodejs.org/dist/v14.21.3/node-v14.21.3-linux-x64.tar.xz...
1:04:21 PM: Computing checksum with sha256sum
1:04:21 PM: Checksums matched!
1:04:23 PM: Now using node v14.21.3 (npm v6.14.18)
1:04:23 PM: Enabling Node.js Corepack
1:04:23 PM: Started restoring cached build plugins
1:04:23 PM: Finished restoring cached build plugins
1:04:23 PM: Started restoring cached corepack dependencies
1:04:23 PM: Finished restoring cached corepack dependencies
1:04:23 PM: No npm workspaces detected
1:04:23 PM: Started restoring cached node modules
1:04:23 PM: Finished restoring cached node modules
1:04:23 PM: Installing npm packages using npm version 6.14.18
1:04:25 PM: npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
1:04:35 PM: npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
1:04:38 PM: npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
1:04:40 PM: npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
1:04:40 PM: npm WARN deprecated workbox-cacheable-response@6.6.0: workbox-background-sync@6.6.0
1:04:40 PM: npm WARN deprecated workbox-google-analytics@6.6.0: It is not compatible with newer versions of GA starting with v4, as long as you are using GAv3 it should be ok, but the package is not longer being maintained
1:04:40 PM: npm WARN deprecated core-js@1.2.7: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
1:04:42 PM: npm WARN deprecated abab@2.0.6: Use your platform"s native atob() and btoa() methods instead
npm WARN deprecated domexception@2.0.1: Use your platform"s native DOMException instead
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform"s native performance.now() and performance.timeOrigin.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
1:04:42 PM: npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
1:04:43 PM: npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
1:04:43 PM: npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
1:04:43 PM: npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
1:05:20 PM: > husky@4.3.8 install /opt/build/repo/node_modules/husky
1:05:20 PM: > node husky install
1:05:20 PM: husky > Setting up git hooks
1:05:20 PM: CI detected, skipping Git hooks installation.
1:05:20 PM: husky > Done
1:05:20 PM: > core-js@2.6.12 postinstall /opt/build/repo/node_modules/core-js
1:05:20 PM: > node -e "try{require("./postinstall")}catch(e){}"
1:05:20 PM: > husky@4.3.8 postinstall /opt/build/repo/node_modules/husky
1:05:20 PM: > opencollective-postinstall || exit 0
1:05:21 PM: npm notice created a lockfile as package-lock.json. You should commit this file.
1:05:21 PM: npm WARN notsup Unsupported engine for next@13.5.6: wanted: {"node":">=16.14.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
1:05:21 PM: npm WARN notsup Not compatible with your version of node/npm: next@13.5.6
1:05:21 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-arm64@13.5.6 (node_modules/next/node_modules/@next/swc-darwin-arm64):
1:05:21 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-arm64@13.5.6: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
1:05:21 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-x64@13.5.6 (node_modules/next/node_modules/@next/swc-darwin-x64):
1:05:21 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-x64@13.5.6: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
1:05:21 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm64-gnu@13.5.6 (node_modules/next/node_modules/@next/swc-linux-arm64-gnu):
1:05:21 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm64-gnu@13.5.6: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
1:05:21 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm64-musl@13.5.6 (node_modules/next/node_modules/@next/swc-linux-arm64-musl):
1:05:21 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm64-musl@13.5.6: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
1:05:21 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-arm64-msvc@13.5.6 (node_modules/next/node_modules/@next/swc-win32-arm64-msvc):
1:05:21 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-arm64-msvc@13.5.6: wanted {"os":"win32","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
1:05:21 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-ia32-msvc@13.5.6 (node_modules/next/node_modules/@next/swc-win32-ia32-msvc):
1:05:21 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-ia32-msvc@13.5.6: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
1:05:21 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-x64-msvc@13.5.6 (node_modules/next/node_modules/@next/swc-win32-x64-msvc):
1:05:21 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-x64-msvc@13.5.6: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
1:05:21 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/rollup/node_modules/fsevents):
1:05:21 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
1:05:21 PM: npm WARN dotenv-webpack@2.0.0 requires a peer of webpack@^1 || ^2 || ^3 || ^4 but none is installed. You must install peer dependencies yourself.
1:05:21 PM: npm WARN nextjs-progressbar@0.0.6 requires a peer of next@^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 but none is installed. You must install peer dependencies yourself.
1:05:21 PM: npm WARN nextjs-progressbar@0.0.6 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
1:05:21 PM: npm WARN react-datepicker@3.8.0 requires a peer of react@^16.9.0 || ^17 but none is installed. You must install peer dependencies yourself.
1:05:21 PM: npm WARN react-datepicker@3.8.0 requires a peer of react-dom@^16.9.0 || ^17 but none is installed. You must install peer dependencies yourself.
1:05:21 PM: npm WARN react-number-format@4.4.1 requires a peer of react@^0.14 || ^15.0.0-rc || ^15.0.0 || ^16.0.0-rc || ^16.0.0 but none is installed. You must install peer dependencies yourself.
1:05:21 PM: npm WARN react-number-format@4.4.1 requires a peer of react-dom@^0.14 || ^15.0.0-rc || ^15.0.0 || ^16.0.0-rc || ^16.0.0 but none is installed. You must install peer dependencies yourself.
1:05:21 PM: npm WARN react-reveal@1.2.2 requires a peer of react@^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
1:05:21 PM: npm WARN react-spinners@0.9.0 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
1:05:21 PM: npm WARN react-spinners@0.9.0 requires a peer of react-dom@^16.0.0 but none is installed. You must install peer dependencies yourself.
1:05:21 PM: npm WARN babel-loader@8.3.0 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
1:05:21 PM: npm WARN terser-webpack-plugin@5.3.10 requires a peer of webpack@^5.1.0 but none is installed. You must install peer dependencies yourself.
1:05:21 PM: npm WARN clean-webpack-plugin@4.0.0 requires a peer of webpack@>=4.0.0 <6.0.0 but none is installed. You must install peer dependencies yourself.
1:05:21 PM: npm WARN workbox-webpack-plugin@6.6.0 requires a peer of webpack@^4.4.0 || ^5.9.0 but none is installed. You must install peer dependencies yourself.
1:05:21 PM: npm WARN @apideck/better-ajv-errors@0.3.6 requires a peer of ajv@>=8 but none is installed. You must install peer dependencies yourself.
1:05:21 PM: npm WARN react-popper@1.3.11 requires a peer of react@0.14.x || ^15.0.0 || ^16.0.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
1:05:21 PM: npm WARN @typescript-eslint/eslint-plugin@3.10.1 requires a peer of eslint@^5.0.0 || ^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
1:05:21 PM: npm WARN @typescript-eslint/parser@3.10.1 requires a peer of eslint@^5.0.0 || ^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
1:05:21 PM: added 1303 packages from 724 contributors and audited 1314 packages in 57.629s
1:05:21 PM: 181 packages are looking for funding
1:05:21 PM:   run `npm fund` for details
1:05:22 PM: found 2 vulnerabilities (1 low, 1 high)
1:05:22 PM:   run `npm audit fix` to fix them, or `npm audit` for details
1:05:22 PM: npm packages installed
1:05:22 PM: Successfully installed dependencies
1:05:22 PM: Starting build script
1:05:25 PM: Detected 1 framework(s)
1:05:25 PM: "next" at version "13.5.6"
1:05:25 PM: Section completed: initializing
1:05:27 PM: 
1:05:27 PM: Netlify Build                                                 
1:05:27 PM: ────────────────────────────────────────────────────────────────
1:05:27 PM: 
1:05:27 PM: ❯ Version
1:05:27 PM:   @netlify/build 29.36.5
1:05:27 PM: 
1:05:27 PM: ❯ Flags
1:05:27 PM:   baseRelDir: true
1:05:27 PM:   buildId: 6602b9ab55b2e52303d67b26
1:05:27 PM:   deployId: 6602b9ab55b2e52303d67b28
1:05:27 PM: 
1:05:27 PM: ❯ Current directory
1:05:27 PM:   /opt/build/repo
1:05:27 PM: 
1:05:27 PM: ❯ Config file
1:05:27 PM:   No config file was defined: using default values.
1:05:27 PM: 
1:05:27 PM: ❯ Context
1:05:27 PM:   production
1:05:27 PM: 
1:05:27 PM: ❯ Installing plugins
1:05:27 PM:    - @netlify/plugin-nextjs@4.41.3
1:05:38 PM: 
1:05:38 PM: ❯ Using Next.js Runtime - v4.41.3
1:05:39 PM: 
1:05:39 PM: @netlify/plugin-nextjs (onPreBuild event)                     
1:05:39 PM: ────────────────────────────────────────────────────────────────
1:05:39 PM: 
1:05:39 PM: No Next.js cache to restore.
1:05:39 PM: Not running Next Runtime
1:05:39 PM: 
1:05:39 PM: (@netlify/plugin-nextjs onPreBuild completed in 13ms)
1:05:39 PM: 
1:05:39 PM: Build command from Netlify app                                
1:05:39 PM: ────────────────────────────────────────────────────────────────
1:05:39 PM: 
1:05:39 PM: $ yarn start
1:05:39 PM: yarn run v1.22.19
1:05:39 PM: $ next start
1:05:40 PM: Failed during stage "building site": Build script returned non-zero exit code: 2
1:05:40 PM: /opt/build/repo/node_modules/next/dist/bin/next:57
1:05:40 PM: performance.mark("next-start");
1:05:40 PM: ^
1:05:40 PM: ReferenceError: performance is not defined
1:05:40 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/next/dist/bin/next:57:1)
1:05:40 PM:     at Module._compile (internal/modules/cjs/loader.js:1114:14)
1:05:40 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
1:05:40 PM:     at Module.load (internal/modules/cjs/loader.js:979:32)
1:05:40 PM:     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
1:05:40 PM:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
1:05:40 PM:     at internal/main/run_main_module.js:17:47
1:05:40 PM: error Command failed with exit code 1.
1:05:40 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
1:05:40 PM: 
1:05:40 PM: "build.command" failed                                        
1:05:40 PM: ────────────────────────────────────────────────────────────────
1:05:40 PM: 
1:05:40 PM:   Error message
1:05:40 PM:   Command failed with exit code 1: yarn start
1:05:40 PM: 
1:05:40 PM:   Error location
1:05:40 PM:   In Build command from Netlify app:
1:05:40 PM:   yarn start
1:05:40 PM: 
1:05:40 PM:   Resolved config
1:05:40 PM:   build:
1:05:40 PM:     command: yarn start
1:05:40 PM:     commandOrigin: ui
1:05:40 PM:     environment:
1:05:40 PM:       - NETLIFY_NEXT_PLUGIN_SKIP
1:05:40 PM:     publish: /opt/build/repo/.next
1:05:40 PM:     publishOrigin: ui
1:05:40 PM:   plugins:
1:05:40 PM:     - inputs: {}
1:05:40 PM:       origin: ui
1:05:40 PM:       package: "@netlify/plugin-nextjs"
1:05:40 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
1:05:40 PM: Failing build: Failed to build site
1:05:40 PM: Finished processing build request in 1m31.54s
